name: dio_retry
description: A starting point for Dart libraries or applications.
version: 0.1.10-beta
homepage: https://github.com/aloisdeniel/dio_retry

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  logging: ^0.11.3
  dio: ^4.0.6

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
